spring.application.name=sb-ecom

spring.output.ansi.enabled=ALWAYS

logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){green} %clr(%-5level){blue} %clr([%thread]){cyan} %clr(%logger{40}){yellow} : %msg%n

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

project.image=images/

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update

spring.app.jwtSecret=mySecretKey123912738odkfoawjigsdfjspkfiwehf8wesaqwpkdqdpkl
spring.app.jwtExpirationMs=3000000

# Logger
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.project=DEBUG