spring.application.name=sb-ecom

spring.output.ansi.enabled=ALWAYS

logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){green} %clr(%-5level){blue} %clr([%thread]){cyan} %clr(%logger{40}){yellow} : %msg%n

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update